### ISSUE TITLE
Confirmatory pop-ups of the file io options 

### ISSUE THREAD

**Issue by 1-Harshit** [1-Harshit/ed-eater#22]
> **Save**: Generates a ed-eater.txt file of the current editor contents
> **Open**: Opens a .txt file in the editor
> **Clear Editor**: Clears the current contents of the editor

> Confirmatory pop-ups of the three options are yet to be implemented

_Originally posted by @rashmigr01 in https://github.com/1-Harshit/ed-eater/issues/21#issuecomment-1755980747_

**Comment by 1-Harshit** [comment]
I think this is stale now, should we close this issue? @rashmigr01

**Comment by rashmigr01** [comment]
> I think this is stale now, should we close this issue? @rashmigr01

Yup! Don't see this being done for this milestone.
