### ISSUE TITLE
UI UX Intial Designs

### ISSUE THREAD

**Issue by 1-Harshit** [1-Harshit/ed-eater#5]

**Comment by rashmigr01** [comment]
# Initial UI UX concept diagram:

![ed-eater-design](https://github.com/1-Harshit/ed-eater/assets/77162931/81eb2c6d-43d7-4b32-aa2d-d1302fb795ce)

## In the web view,
* The upper pane consists of the **file IO**, **editing tools**, and **additional feature** implementations in that order.
* The middle pane is the tab area, which allows the creation and opening of various **tabs**.
* The bottom text area serves as the editor with **key bindings**, **copy-paste**, and other operational features.

## In the mobile view,
* The top panel only opens to the **current tab** and has a **more** button with all features collapsed into it.
* The bottom **text area** keeps the editor in focus and contains the text.

## Other Notes:
* Further collapsibility of various features in the upper pane of the web view with window resizing will help keep the design **responsive**.
* The **more** button in the upper panel holds all features collapsed with lowered window sizes.
* The text area should occupy more than **60%** of the screen space in all cases to ensure the focus stays on the editor.
